import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "../utils/ReactQueryProvider";
import { Header } from "../components/Header";
import { CreateQuizForm } from "../components/CreateQuizForm";
import { BreadcrumbComponent } from "../components/Breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center flex-col`}
      >
        <ReactQueryProvider>

          <Header />
          <BreadcrumbComponent />

          {children}
          <CreateQuizForm />
        </ReactQueryProvider>

      </body>
    </html>
  );
}
